server:

  port: 8980
  context-path: /
  tomcat:
    uri-encoding: UTF-8

spring:

  profiles:
    active: default
    
  main:
    banner-mode: "off"

# 产品或项目名称、软件开发公司名称
productName: JeeSite Demo
companyName: ThinkGem

# 产品版本、版权年份
productVersion: V4.0
copyrightYear: 2018

# 数据库连接
jdbc:

  # Mysql 数据库配置
  type: mysql
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3307/jeesite?useSSL=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
  username: jeesite
  password: jeesite
  testSql: SELECT 1